TrajectoryPlannerROS:
  acc_lim_x: 0.8
  acc_lim_theta: 1.0
  max_vel_x: 0.2
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 1.0
  holonomic_robot: false
  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.1
  pdist_scale: 1.0
  gdist_scale: 1.0 
  occdist_scale: 0.05
  meter_scoring: true
  sim_granularity: 0.04
