global_costmap:
  global_frame: map
  robot_base_frame: base_link 
  update_frequency: 1.0
  publish_frequency: 1.0
  resolution: 0.05
  static_map: true
  rolling_window: false
  transform_tolerance: 2.0
  cost_scaling_factor: 5.0
  infration_radius: 0.10
  width: 10.0
  height: 10.0
