local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  width: 5.5
  height: 5.5
  resolution: 0.1
  static_map: false
  rolling_window: true
  transform_tolerance: 2.0 
  cost_scaling_factor: 0.5
  inflation_radius: 0.1
  
