shutdown_costmaps: True

controller_frequency: 2 
controller_patience: 15.0

planner_frequency: 2
planner_patience: 20

oscillation_timeout: 0.0
oscillation_distance: 0.5

#clearing_rotation_allowed: False 
#clearing_go_forward_allowed: False 

base_local_planner: "base_local_planner/TrajectoryPlannerROS"
#base_local_planner: "dwa_local_planner/DWAPlannerROS"
